---
- name: tap caskroom/cask
  homebrew_tap:
    tap: caskroom/cask
    state: present

- name: install
  homebrew:
    name: brew-cask
    state: present
  ignore_errors: yes

- name: tap caskroom/versions
  homebrew_tap:
    tap: caskroom/versions
    state: present
